### PR TITLE
Feat post tests

### PR DESCRIPTION
**Pull request by ali-phipps**
Added orderly gem to help test order of posts in feature test

### CODE REVIEW

**Review by emmavanoss — DISMISSED** [review]

**Comment by emmavanoss** [comment]
This branch is failing the travis build, probably because the latest Travis config file (which resolves issues with bundler) isn't in here.
I suggest:
1) Rebase the branch with the master, so we have the up to date config for Travis
2) Delete Gemfile.lock and rerun bundle to make sure all the latest versions of the gems are installed

**Comment by emmavanoss** [comment]
This branch is failing the travis build, probably because the latest Travis config file (which resolves issues with bundler) isn't in here.
I suggest:

1) Rebase the branch with the master, so we have the up to date config for Travis
2) Delete Gemfile.lock and rerun bundle to make sure all the latest versions of the gems are installed

**Review by KOlofinmoyin — DISMISSED** [review]
Ready to go, thanks.

**Comment by ali-phipps** [comment]
got in a mess, will close and reopen

**Comment by ali-phipps** [comment]
d

**Review by KOlofinmoyin — APPROVED** [review]
yes

**Pull request merged**
